# Site settings
title: Effy West
email: you@example.com
description: Counselling and psychotherapy in London
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: therapywindow
github_username:  therapywindow

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: false
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/


